# Generated by Django 5.0.6 on 2024-05-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('qualification_percentage', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField()),
                ('no_of_backlogs', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='employee_resumes')),
            ],
        ),
    ]
