# Generated by Django 5.0.6 on 2024-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='no_of_backlogs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='qualification_percentage',
            field=models.IntegerField(),
        ),
    ]
