# Generated by Django 5.0.6 on 2024-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employeemodel_no_of_backlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('req_skills', models.CharField(max_length=500)),
                ('req_qualifications', models.CharField(max_length=500)),
                ('salary', models.IntegerField()),
                ('contact_number', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
