# Generated by Django 5.0.6 on 2024-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='image',
            field=models.ImageField(default='https://st4.depositphotos.com/14953852/24787/v/450/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg', upload_to='company_images'),
        ),
    ]
