# Generated by Django 5.0.6 on 2024-06-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_companymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='applied_to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.companymodel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='image',
            field=models.ImageField(upload_to='company_images'),
        ),
    ]
