# Generated by Django 5.0.6 on 2024-06-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employeemodel_applied_to_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='applied_to_company',
        ),
    ]
