# Generated by Django 5.0.6 on 2024-06-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_applicationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationModel',
        ),
    ]
