# Generated by Django 5.0.2 on 2024-07-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='position_name',
            field=models.CharField(default='no', max_length=100),
            preserve_default=False,
        ),
    ]
